# Generated by Django 5.0.7 on 2024-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='tokens',
            new_name='contracts',
        ),
        migrations.AddField(
            model_name='wallet',
            name='fungibles',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='native',
            field=models.JSONField(null=True),
        ),
    ]
