# Generated by Django 5.0.7 on 2024-08-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tokens_wallet_contracts_wallet_fungibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='contracts',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='fungibles',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='native',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transactions',
        ),
    ]
