// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftPreviewSerializer
// Digest: 21f4a74343f6149e6ad5a77c7355a2a2f6ccd8f87d181b999c6c0a2374a51994
// Last modified on: 2024-08-03T16:25:33.726363

export interface NftPreview {
  image_small_url: string;
  image_medium_url: string;
  image_large_url: string;
  image_opengraph_url: string;
  blurhash: string;
  predominant_color: string;
}