// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftCollectionRoyaltiesSerializer
// Digest: 95527278bcbc9e1b258ddcde5855d9a63d6fb38d70de2fc9b74cd9aea64924cd
// Last modified on: 2024-08-03T20:49:49.881104

import { CharField } from './char-field';

export interface NftCollectionRoyalties {
  source: string;
  total_creator_fee_basis_points: string;
  recipients: [];
}