// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftRoyaltySerializer
// Digest: 1faa6e158b6c39216e6450dc8d0dfff96e90a333953928449832581273c13317
// Last modified on: 2024-08-03T20:49:49.886103

import { CharField } from './char-field';

export interface NftRoyalty {
  source: string;
  total_creator_fee_basis_points: number;
  recipients: [];
}