// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftContractSerializer
// Digest: 70b0fa31b2314fa0bd959f42518e8ca6e4346ad5ad7846351836bee614dbb96a
// Last modified on: 2024-08-03T16:25:33.729364

export interface NftContract {
  type: string;
  name: string;
  symbol: string;
  deployed_via_contract: string;
  owned_by: string;
  has_multiple_collections: string;
}