// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftFirstCreatedSerializer
// Digest: ed9f1204358f171e7d271750c574601654e5c92e54984bc04c37801958990332
// Last modified on: 2024-08-03T20:49:49.884100

export interface NftFirstCreated {
  minted_to: string;
  quantity: number;
  quantity_string: string;
  timestamp: string;
  block_number: number;
  transaction: string;
  transaction_initiator: string;
}