// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftImagePropertiesLiteSerializer
// Digest: 691224feb9f8cc70bc99a106bcd65d48532c95e6b182f558bdd1527bbc4f10fe
// Last modified on: 2024-08-03T20:49:49.878104

export interface NftImagePropertiesLite {
  width: number;
  height: number;
  mime_type: string;
}