// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftImagePropertiesSerializer
// Digest: 25d79ae4d8c2e895c16f2fc6e2f9a958d091e48e062f44c30a1d617d83ec8155
// Last modified on: 2024-08-03T20:49:49.875103

export interface NftImageProperties {
  width: number;
  height: number;
  size: number;
  mime_type: string;
  exif_orientation: string;
  predominant_color: string;
}