// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftCollectionSerializer
// Digest: edffc0a44a081ef540c446813241cb21aa8b908dbb3ecbdb17079df9c2d49067
// Last modified on: 2024-08-03T20:49:49.882102

import { CharField } from './char-field';
import { NftCollectionRoyalties } from './nft-collection-royalties';
import { NftImageProperties } from './nft-image-properties';
import { NftMarketplacePage } from './nft-marketplace-page';

export interface NftCollection {
  collection_id: string;
  name: string;
  description: string;
  image_url: string;
  image_properties: NftImageProperties;
  banner_image_url: string;
  category: string;
  is_nsfw: string;
  external_url: string;
  twitter_username: string;
  discord_url: string;
  instagram_username: string;
  medium_username: string;
  telegram_url: string;
  marketplace_pages: NftMarketplacePage[];
  metaplex_mint: string;
  metaplex_candy_machine: string;
  metaplex_first_verified_creator: string;
  floor_prices: string;
  top_bids: string;
  distinct_owner_count: number;
  distinct_nft_count: number;
  total_quantity: number;
  chains: [];
  top_contracts: [];
  collection_royalties: NftCollectionRoyalties[];
}