// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftRaritySerializer
// Digest: 093fa722da0500fc8aa31f5ad34a9b82e79a543a79af01019ca86b544251b9f9
// Last modified on: 2024-08-03T20:49:49.885105

export interface NftRarity {
  rank: string;
  score: string;
  unique_attributes: string;
}