// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftExtraMetadataSerializer
// Digest: c12d3acb82867bcbcf237845c97f14baea86c03b3724b14444db147f064f9459
// Last modified on: 2024-08-03T20:49:49.890103

import { CharField } from './char-field';

export interface NftExtraMetadata {
  attributes: [];
  image_original_url: string;
  animation_original_url: string;
  metadata_original_url: string;
}