// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftOwnersSerializer
// Digest: 9cd7226e3ddf600652e0333116ff853eb5c6eb6427ffb9836f92421e67cf8789
// Last modified on: 2024-08-03T16:25:33.728365

export interface NftOwners {
  owner_address: string;
  quantity: number;
  quantity_string: string;
  first_acquired_date: string;
  last_acquired_date: string;
}