// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.NftMarketplacePageSerializer
// Digest: ede6a38879d9395527b87fef3641058f19e986ecad6fc6656f1f0b358319ca29
// Last modified on: 2024-08-03T20:49:49.879106

export interface NftMarketplacePage {
  marketplace_id: string;
  marketplace_name: string;
  marketplace_collection_id: string;
  nft_url: string;
  collection_url: string;
  verified: boolean;
}