// This file is generated by django-rest-tsg@0.1.10.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: api.models.proxies.SimpleHash.WalletSerializer
// Digest: bae3b59bb82a78e121c70500c6e633aacc6a7249e37b6000f266d983998931b3
// Last modified on: 2024-08-03T16:25:33.732351

import { NftResult } from './nft-result';
import { TransactionResult } from './transaction-result';

export interface Wallet {
  nfts: NftResult[];
  tokens: TransactionResult[];
  transactions: TransactionResult[];
}